version: '3.8'

services:
  db:
    image: postgres:14.3
    volumes:
      - ${PG_DATA_OVERRIDE-/tmp/idpartner/pg_data}:/var/lib/postgresql/data
      - ./scripts/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: welcome1

  redis:
    image: redis:6.2.6
    restart: always
    ports:
      - "6379:6379"

  bank-oidc-provider-example:
    # image: 535716075523.dkr.ecr.us-west-2.amazonaws.com/idpartner-mock-bank-oidc-example-service:development 
    image: idpartner-mock-bank-oidc-example-service
    restart: always
    # pull_policy: always
    ports:
      - "9101:9101"
    environment:
      ### Common Config
      AUTHORIZATION_ISSUER_CLIENT_ID: foo
      AUTHORIZATION_ISSUER_CLIENT_SECRET: bar
      AUTHORIZATION_ISSUER_URL: http://docker.for.mac.localhost:9101
      AUTHORIZATION_PROXY_CALLBACK_URL: CHANGE_ME_AUTHORIZATION_ADAPTER_SERVICE_NGROK/v1/auth/callback
      BASE64_JWKS: BASE64:CHANGE_ME
      PORT: 9101

      ### Redis Config
      REDIS_HOST: docker.for.mac.localhost
      # REDIS_PORT: 6379

      ### Session Config
      COOKIE_SECRET: RANDOM:CHANGE_ME

      ### Stytch Config
      STYTCH_API_URL: https://test.stytch.com/v1
      STYTCH_API_USERNAME: STYTCH_USERNAME:CHANGE_ME
      STYTCH_API_PASSWORD: STYTCH_PASSWORD:CHANGE_ME
    depends_on:
      - redis

  authorization-adapter-service:
    # image: 535716075523.dkr.ecr.us-west-2.amazonaws.com/idpartner-authorization-adapter-service:development 
    image: idpartner-authorization-adapter-service
    restart: always
    # pull_policy: always
    ports:
      - "9102:9102"
    environment:
      ### Common Config
      AUTHORIZATION_ADAPTER_URL: CHANGE_ME_AUTHORIZATION_ADAPTER_SERVICE_NGROK
      OIDC_SERVICE_URL: CHANGE_ME_OIDC_PROVIDER_SERVICE_NGROK
      PORT: 9102

      ### Redis Config
      REDIS_HOST: docker.for.mac.localhost
      # REDIS_PORT: 6379

      ### Session Config
      COOKIE_DOMAIN: HANGE_ME:AUTHORIZATION_ADAPTER_SERVICE_WITHOUT_SCHEME_NGROK
      COOKIE_SECRET: RANDOM:CHANGE_ME

      ### Error Reporting Config
      SENTRY_DSN: https://xxx@yyy.ingest.sentry.io/000

      ### (Common) Auth Config
      OAUTH_PROTOCOL: oauth2
      OAUTH_URL: http://docker.for.mac.localhost:9101
      OAUTH_CLIENT_ID: foo
      OAUTH_CLIENT_SECRET: bar
      # OAUTH_PKCE_ENABLED: true

      ### (OAuth2) Auth Config - Specify config below only if using OAuth2
      OAUTH_USERINFO_PATH: /me
      OAUTH_TOKEN_PATH: /token
      OAUTH_AUTHORIZATION_PATH: /auth
    depends_on:
      - redis

  oidc-provider-service:
    # image: 535716075523.dkr.ecr.us-west-2.amazonaws.com/idpartner-oidc-provider-service:development 
    image: idpartner-oidc-provider-service
    restart: always
    # pull_policy: always
    ports:
      - "9001:9001"
    environment:
      ### Common Config
      BASE64_JWKS: BASE64:CHANGE_ME
      IDENTITY_PROVIDER_UUID: IDPARTNER_IDP_UUID:CHANGE_ME
      OIDC_COOKIES_KEYS: RANDOM:CHANGE_ME
      OIDC_SERVICE_URL: CHANGE_ME_OIDC_PROVIDER_SERVICE_NGROK
      PORT: 9001

      ### Database Config
      SQL_DATABASE: idpartner
      SQL_HOST: docker.for.mac.localhost
      SQL_PASSWORD: postgres
      SQL_USER: postgres
      # PGSSLMODE: disable

      ### Redis Config
      REDIS_HOST: docker.for.mac.localhost
      # REDIS_PORT: 6379

      ### Session Config
      COOKIE_DOMAIN: CHANGE_ME_OIDC_PROVIDER_SERVICE_NGROK_WITHOUT_SCHEME
      COOKIE_SECRET: RANDOM:CHANGE_ME

      ### Error Reporting Config
      SENTRY_DSN: https://xxx@yyy.ingest.sentry.io/000

      ### IDPartner Services Config
      BROKER_SERVICE_URL: http://docker.for.mac.localhost:9002
      EVENT_SERVICE_URL: http://docker.for.mac.localhost:9005
      TRUST_MANAGEMENT_SERVICE_URL: http://docker.for.mac.localhost:9004

      ### IDP Services Config
      AUTH_SERVICE_URL: https://d76c434b736b.ngrok.io
      # TRUSTED_PACKAGE_VERIFICATION_API_AUTH_TOKEN_TTL_IN_SECONDS: 60
      # TRUSTED_PACKAGE_VERIFICATION_API: http://docker.for.mac.localhost:9100/v1/trusted-packages/verify
      # TRUSTED_PACKAGE_VERIFICATION_ENABLED: true
    depends_on:
      - db
      - redis
