version: '3.8'

services:
  db:
    image: postgres:14.3
    volumes:
      - ${PG_DATA_OVERRIDE-/tmp/idpartner/pg_data}:/var/lib/postgresql/data
      - ./scripts/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: welcome1

  redis:
    image: redis:6.2.6
    restart: always
    ports:
      - "6379:6379"

  bank-identity-example-services:
    image: idpartner-mock-bank-identity-service
    restart: always
    ports:
      - "9702:9702"
    environment:
      AUTHORIZATION_ISSUER_CLIENT_ID: CHANGE_ME-CLIENT_ID
      AUTHORIZATION_ISSUER_CLIENT_SECRET: CHANGE_ME-CLIENT_SECRET
      AUTHORIZATION_ISSUER_URL: http://docker.for.mac.localhost:9702
      AUTHORIZATION_PROXY_CALLBACK_URL: CHANGE_ME-TRUST_PLATFORM_SERVICES_NGROK/auth-adapter/v1/auth/callback
      BASE64_JWKS: CHANGE_ME-BASE64_JWKS
      BANK_IDENTITY_SERVICE_URL: http://docker.for.mac.localhost:9702
      BASE64_FIREBASE_PRIVATE_KEY: e30K
      COOKIE_SECRET: CHANGE_ME-RANDOM_SECRET
      PGSSLMODE: disable
      PORT: 9702
      SQL_DATABASE: idpartner
      SQL_USER: postgres
      SQL_PASSWORD: welcome1
      SQL_HOST: docker.for.mac.localhost
      SQL_PORT: 5432
      REDIS_HOST: docker.for.mac.localhost
      REDIS_PORT: 6379
      SENTRY_DSN: https://xxx@yyy.ingest.sentry.io/000
      STYTCH_API_URL: https://test.stytch.com/v1
      STYTCH_API_PROJECT_ID: CHANGE_ME-STYTCH_API_PROJECT_ID
      STYTCH_API_SECRET: CHANGE_ME-STYTCH_API_SECRET
    depends_on:
      - db
      - redis

  trust-platform-services:
    image: idpartner-oidc-provider-service
    restart: always
    ports:
      - "9501:9501"
    environment:
      ### Common Config
      BASE64_JWKS: CHANGE_ME-BASE64_JWKS
      IDENTITY_PROVIDER_UUID: CHANGE_ME-IDENTITY_PROVIDER_UUID
      OIDC_COOKIES_KEYS: CHANGE_ME-RANDOM_SECRET
      OIDC_SERVICE_URL: CHANGE_ME-TRUST_PLATFORM_SERVICES_NGROK/oidc
      PORT: 9501

      ### Database Config
      SQL_DATABASE: idpartner
      SQL_HOST: docker.for.mac.localhost
      SQL_PASSWORD: welcome1
      SQL_USER: postgres
      PGSSLMODE: disable

      ### Redis Config
      REDIS_HOST: docker.for.mac.localhost
      # REDIS_PORT: 6379

      ### Session Config
      COOKIE_DOMAIN: CHANGE_ME-TRUST_PLATFORM_SERVICES_NGROK_WITHOUT_SCHEME
      COOKIE_SECRET: CHANGE_ME-RANDOM_SECRET

      ### Error Reporting Config
      SENTRY_DSN: https://xxx@yyy.ingest.sentry.io/000

      ### IDP Services Config
      TRUSTED_PACKAGE_VERIFICATION_API: http://docker.for.mac.localhost:9702/v1/trusted-packages/verify
      TRUSTED_PACKAGE_VERIFICATION_ENABLED: true

      ### (Common) Auth Config
      OAUTH_PROTOCOL: oauth2
      OAUTH_URL: http://docker.for.mac.localhost:9701
      OAUTH_CLIENT_ID: CHANGE_ME-CLIENT_ID
      OAUTH_CLIENT_SECRET: CHANGE_ME-CLIENT_SECRET
      # OAUTH_PKCE_ENABLED: true

      ### (OAuth2) Auth Config - Specify config below only if using OAuth2
      OAUTH_USERINFO_PATH: /me
      OAUTH_TOKEN_PATH: /token
      OAUTH_AUTHORIZATION_PATH: /auth

      ### IDP Services Config
      MOBILE_APP_URL: CHANGE_ME-MOBILE_APP_URL
      BANK_AUTH_SERVICE_TOKEN_VERIFY_API: http://docker.for.mac.localhost:9702/v1/auth/verify
      BANK_USERS_SERVICE_API: http://docker.for.mac.localhost:9702/v1/users
      BANK_DEVICES_SERVICE_API: http://docker.for.mac.localhost:9702/v1/devices
      BANK_PUSH_AUTHENTICATIONS_SERVICE_API: http://docker.for.mac.localhost:9702/v1/push-authentications
    depends_on:
      - db
      - redis
